all:
	g++ -ggdb -gdwarf-2 MainProgram.cpp RandomNumberGrabber.cpp Event.cpp Process.cpp Scheduler.cpp FCFSScheduler.cpp LCFSScheduler.cpp SJFScheduler.cpp RRScheduler.cpp PRIOScheduler.cpp -o output.out
