all:
	#g++-4.8 -std=c++0x Symbol.cpp Linker.cpp MainProgram.cpp Module.cpp Operation.cpp -o output.out
	g++-4.8 -ggdb -std=c++0x Symbol.cpp Linker.cpp MainProgram.cpp Module.cpp Operation.cpp -o output.out
