all:
	#g++48 Symbol.cpp Linker.cpp MainProgram.cpp Module.cpp Operation.cpp -o output.out
	#g++48 -ggdb Symbol.cpp Linker.cpp MainProgram.cpp Module.cpp Operation.cpp -o output.out
	g++ -gdwarf-2 Symbol.cpp Linker.cpp MainProgram.cpp Module.cpp Operation.cpp -o output.out
